// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {HonkVerifier} from "../src/HonkVerifier.sol";
import {RevealVerifier, INoirVerifier} from "../src/RevealVerifier.sol";

/// @notice Ring 3, the cut line, proven for real. Deploys the bb-generated UltraHonk
///         verifier and checks that the REAL Noir proof (from circuits/reveal/target)
///         verifies on chain, and that RevealVerifier emits the green tick. The route
///         stays private: only the public inputs (commitment, cap, spend, target) and
///         the proof are on chain.
contract RevealTest is Test {
    HonkVerifier internal verifier;
    RevealVerifier internal reveal;

    bytes internal proofBytes;
    bytes32[] internal publicInputs;

    bytes32 internal constant ROUND = bytes32(uint256(0x3fa9));
    bytes32 internal constant AGENT = keccak256("adaptive");

    event RevealVerified(bytes32 indexed roundId, bytes32 indexed agentId, bool ok);

    function setUp() public {
        verifier = new HonkVerifier();
        reveal = new RevealVerifier(INoirVerifier(address(verifier)));

        // The real proof, generated by bb from the real circuit and committed as a
        // fixture so this test runs on a fresh clone without the Noir toolchain.
        // Regenerate with: cd circuits/reveal && nargo execute witness && \
        //   bb prove --scheme ultra_honk -b target/reveal.json -w target/witness.gz \
        //     -o target --oracle_hash keccak
        proofBytes = vm.readFileBinary("test/fixtures/reveal/proof");

        // The 4 public inputs, in order: commitment, cap, spent, quality_target.
        // (The 8 pairing-point inputs the verifier needs are carried inside the proof.)
        publicInputs = new bytes32[](4);
        publicInputs[0] = 0x1a4fa51bbad114b05e3205f0b8059a1811b347973d9ac7743da4e21016b42851; // commitment
        publicInputs[1] = bytes32(uint256(1_000_000_000_000_000_000)); // cap 1.00 OKB
        publicInputs[2] = bytes32(uint256(970_000_000_000_000_000)); // spent 0.97 OKB
        publicInputs[3] = bytes32(uint256(80)); // quality target
    }

    /// The UltraHonk verifier accepts the real proof on chain.
    function test_verifier_acceptsRealProof() public view {
        assertTrue(verifier.verify(proofBytes, publicInputs), "real Honk proof must verify on chain");
    }

    /// RevealVerifier emits the green tick. The route is never revealed.
    function test_reveal_emitsGreenTick() public {
        vm.expectEmit(true, true, false, true);
        emit RevealVerified(ROUND, AGENT, true);
        reveal.reveal(ROUND, AGENT, proofBytes, publicInputs);
    }

    /// A tampered public input (claiming a lower spend than the proof commits to) is
    /// rejected. The verifier reverts on a mismatched proof, so a staticcall that fails
    /// is the rejection: verification does not pass.
    function test_verifier_rejectsTamperedPublicInput() public view {
        bytes32[] memory tampered = new bytes32[](4);
        tampered[0] = publicInputs[0];
        tampered[1] = publicInputs[1];
        tampered[2] = bytes32(uint256(500_000_000_000_000_000)); // lie: 0.50 spent
        tampered[3] = publicInputs[3];
        (bool ok,) = address(verifier).staticcall(
            abi.encodeWithSignature("verify(bytes,bytes32[])", proofBytes, tampered)
        );
        assertFalse(ok, "a tampered public input must not verify");
    }
}
